import { Employee } from './employee.model';

export const ELEMENT_DATA: Employee[] = [
  {
    userId: 'ewf',
    status: 'asdasd',
    firstName: 'sdfsdf',
    middleName: 'asdas',
    lastName: 'asda',
    gender: 'dfsdf',
    dateOfBirth: 'aSas',
    idType: 'dfsdf',
    idNumber: 'asda',
    employmentType: 'dfsdf',
    employmentStatus: 'asda',
    dateOfJoining: 'asda',
    dateOfLeaving: 'fdsf',
    basicSal: 'asdas',
    allowance: 'asda',
    grossSal: 'asdasd',
    statutoryDeductions: 'asdasd',
    nonStatutoryDeductions: 'asdasd',
    mobileNo: 'asda',
    emailId: 'asdasd',
    department: 'asdasd',
    supervisorName: 'asdas',
    supervisorMobile: 'asdasd',
    supervisorEmail: 'asdasd',
  },
  {
    userId: 'zxcz',
    status: 'zxcz',
    firstName: 'zxczzxc',
    middleName: 'zxczxc',
    lastName: 'xzcxczx',
    gender: 'zxczxc',
    dateOfBirth: 'zxczxc',
    idType: 'zxczxc',
    idNumber: 'zxczx',
    employmentType: 'zxczxc',
    employmentStatus: 'zxczxc',
    dateOfJoining: 'zxczx',
    dateOfLeaving: 'zxczx',
    basicSal: 'zxczx',
    allowance: 'zxczxc',
    grossSal: 'zxczx',
    statutoryDeductions: 'zxcz',
    nonStatutoryDeductions: 'zxczxc',
    mobileNo: 'zxc',
    emailId: 'zxczxc',
    department: 'zxczx',
    supervisorName: 'zxczxc',
    supervisorMobile: 'zxczxc',
    supervisorEmail: 'zxczxc',
  },
  {
    userId: 'qweqwe',
    status: 'qweqwe',
    firstName: 'qweqwe',
    middleName: 'qweqwe',
    lastName: 'qweqwe',
    gender: 'qweqw',
    dateOfBirth: 'qweqwe',
    idType: 'qweqwe',
    idNumber: 'qweqw',
    employmentType: 'qwe',
    employmentStatus: 'qweqw',
    dateOfJoining: 'qwe',
    dateOfLeaving: 'qwe',
    basicSal: 'qweq',
    allowance: 'qwe',
    grossSal: 'qweq',
    statutoryDeductions: 'qweqw',
    nonStatutoryDeductions: 'qweqwe',
    mobileNo: 'qweqwe',
    emailId: 'qweqwe',
    department: 'qwe',
    supervisorName: 'qweqwe',
    supervisorMobile: 'qwe',
    supervisorEmail: 'qweqweq',
  },

  {
    userId: 'jkljkl',
    status: 'jkljkl',
    firstName: 'jkljkljk',
    middleName: 'jkljkljk',
    lastName: 'jkljkl',
    gender: 'jkljkl',
    dateOfBirth: 'jkljkl',
    idType: 'jkljkljk',
    idNumber: 'jkljkl',
    employmentType: 'jkljkl',
    employmentStatus: 'jkljkl',
    dateOfJoining: 'jkljkl',
    dateOfLeaving: 'jkljkl',
    basicSal: 'jkl',
    allowance: 'jkljkl',
    grossSal: 'jkljkl',
    statutoryDeductions: 'jkljkl',
    nonStatutoryDeductions: 'jkljkl',
    mobileNo: 'jkljkl',
    emailId: 'jkljk',
    department: 'jkljkl',
    supervisorName: 'jkljkl',
    supervisorMobile: 'jkljkl',
    supervisorEmail: 'jlkljk',
  },
  {
    userId: 'bnmbnm',
    status: 'bnmbnm',
    firstName: 'bnmbnm',
    middleName: 'bnmbnm',
    lastName: 'bnmbnm',
    gender: 'bnmbnm',
    dateOfBirth: 'bnmb',
    idType: 'bnmb',
    idNumber: 'bnmbnm',
    employmentType: 'bnmbn',
    employmentStatus: 'bnm',
    dateOfJoining: 'bnmbn',
    dateOfLeaving: 'bnmbn',
    basicSal: 'bnmbn',
    allowance: 'bnm',
    grossSal: 'bnmbnm',
    statutoryDeductions: 'bnm',
    nonStatutoryDeductions: 'bnmbnm',
    mobileNo: 'bnmbnm',
    emailId: 'bnmbnm',
    department: 'bnmbnm',
    supervisorName: 'mbnm',
    supervisorMobile: 'bnmbnm',
    supervisorEmail: 'bnmbnm',
  },
  {
    userId: 'iopiop',
    status: 'iopiop',
    firstName: 'iopiop',
    middleName: 'iopiop',
    lastName: 'iopiop',
    gender: 'iopiop',
    dateOfBirth: 'iopiop',
    idType: 'iopiop',
    idNumber: 'iopio',
    employmentType: 'iopiop',
    employmentStatus: 'iopiop',
    dateOfJoining: 'iopiop',
    dateOfLeaving: 'iopiop',
    basicSal: 'iopiop',
    allowance: 'iopiop',
    grossSal: 'iopiop',
    statutoryDeductions: 'iopiop',
    nonStatutoryDeductions: 'iopiop',
    mobileNo: 'iopiop',
    emailId: 'iopi',
    department: 'iopiop',
    supervisorName: 'iopiop',
    supervisorMobile: 'iopiop',
    supervisorEmail: 'iuopiop',
  },
];
